### ISSUE TITLE
Re-publish package as @celo/compliance instead of compliance-sdk

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/compliance#11]
At the moment this package is published under [`compliance-sdk`](https://www.npmjs.com/package/compliance-sdk/v/1.0.14?activeTab=versions). 

This is not consistent with our other packages, which are published under `@celo/...`.

This makes the package harder to find on npmjs.org and doesn't easily identify it as an `@celo/...` package.

Consider re-publishing the package under `@celo/compliance`
```[tasklist]
### Tasks
- [x] Update package.json and other necessary files in this repo
- [x] Run the publish workflow
- [x] Mark `compliance-sdk` as deprecated with message pointing to `@celo/compliance` (just a new name)
- [x] Publish Github announcement about @celo/compliance vs compliance-sdk name space.
```

**Comment by nicolasbrugneaux** [comment]
- [`@celo/compliance`](https://www.npmjs.com/package/@celo/compliance) published as of [this github action run](https://github.com/celo-org/compliance/actions/runs/7754042081/job/21146557494).
- [`compliance-sdk`](https://www.npmjs.com/package/compliance-sdk) deprecated

**Comment by arthurgousset** [comment]
> * [`@celo/compliance`](https://www.npmjs.com/package/@celo/compliance) published as of [this github action run](https://github.com/celo-org/compliance/actions/runs/7754042081/job/21146557494).
> * [`compliance-sdk`](https://www.npmjs.com/package/compliance-sdk) deprecated

Thank you Nico!
<img width="1184" alt="image" src="https://github.com/celo-org/compliance/assets/46296830/638ee577-5915-437c-bfb2-201f132c2008">

**Comment by arthurgousset** [comment]
Re-opened this issue to not forget to
> Publish Github announcement about @celo/compliance vs compliance-sdk name space.

I'll publish a message in compliance Github Discussions.

**Comment by arthurgousset** [comment]
First need to ask security team to enable Github discussions: https://github.com/celo-org/compliance

Don't currently have permission for that.

**Comment by arthurgousset** [comment]
Github annoucement here: [New NPM package name: @celo/compliance (formerly, compliance-sdk) #19](https://github.com/celo-org/compliance/discussions/19)

Shared on Slack with [DevRel](https://celo-org.slack.com/archives/C01V5UXJ6RY/p1707154518827309) (for Celo Signal), on [compliance channel](https://celo-org.slack.com/archives/C04AU3ERVU1/p1707154481571189) for visibility, and on [Twitter](https://twitter.com/arthurgoussetx/status/1754561169463931076).
