### ISSUE TITLE
Fix celo-compliance Github Action

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/compliance#7]
Context in this [Slack thread](https://celo-org.slack.com/archives/C04AU3ERVU1/p1705079045639529).

Error in Github Action is:

```sh
remote: error: GH006: Protected branch update failed for refs/heads/main.       
remote: error: Changes must be made through a pull request.
```

Source: [Github action](https://github.com/celo-org/compliance/actions/runs/7500057138/job/20418009501#step:7:38)

Github Action seems to fail because direct git push to `main` branch is forbidden according to branch protection policies. 
A GitHub owner or repo admin should be able to update that config
### Tasks
- [x] Ask for elevated permission to temporarily update branch protection policy
- [x] Update OFAC list (incl. repo update and NPM release)
- [x] Check the Github Action updates the list correctly (follow up todo)
- [x] Unpublish mistakenly released NPM package version (for educational reasons)
- [x] https://github.com/celo-org/compliance/issues/11
- [ ] Add alerting if Github Action fails (see #577) - Slack

**Comment by arthurgousset** [comment]
Looks like this stopped working due to a change in branch permissions between Thu, Jan 11 and Fri, Jan 12.

![Image](https://github.com/celo-org/compliance/assets/46296830/dc4b35e0-54f2-4f58-8a4e-186fa2bb648a)

**Comment by arthurgousset** [comment]
Added a todo above

> - [ ] Check the Github Action updates the list correctly (follow up todo)

It looks like the NPM release flow wasn't triggered in the past 3 months. Check this matches with expected updates shared in OFAC feed.

![Image](https://github.com/celo-org/compliance/assets/46296830/c7ed985a-9b59-42c8-ab38-cd9e0f8c0d43)

**Comment by lvpeschke** [comment]
The branch protection, which now requires a PR + approval before committing to the `main` branch, is probably my edit. Last week, I changed security settings across a few repositories working off the premise that additional restrictions, if painful, would be raised.

Ideally, we would keep branch protection going forward, since ensuring all changes to default branches go through PRs adds layers of security (most notably: org-wide workflows such as Socket). This could still get automatically merged, provided all checks pass.

**Comment by arthurgousset** [comment]
Understood, thanks for the heads up @lvpeschke. 

We'll do two things here: 
- make update the workflow to use PR + auto-approval, so the `main` branch protection can stay on
- double-check we get notified when the Github Action fails

It's probably fine to assume that "additional restrictions, if painful, would be raised" if notifications are setup correctly. 

In this case, we happened to check the Gitbub Actions on the day you changed the settings, because Subha manually notified us of an OFAC update.

**Comment by arthurgousset** [comment]
Idea: 
> a slack message that goes to the channel with addreses that were added or if it fails that

**Comment by arthurgousset** [comment]
Idea:
- even update if succeeded but not address was added

**Comment by arthurgousset** [comment]
Note: @shazarre and I will be pairing on this. Leszek is interested in learning more about Github Actions too

**Comment by arthurgousset** [comment]
From Slack: 

> The compliance workflows are broken again, because [branch protection rules were enabled](https://celo-org.slack.com/archives/C014SRL4URY/p1706813016702499?thread_ts=1706793526.957009&cid=C014SRL4URY).
> Just noting this here, so there is a log that this didn't work for the last 2 weeks.
> - Short-term solution: disable branch protection ([like we agreed last time](https://celo-org.slack.com/archives/C04AU3ERVU1/p1705402189521609?thread_ts=1705079045.639529&cid=C04AU3ERVU1))
> - Long-term solution: implement PR-based work-around so pushing to main is not required ([like we agreed last time](https://github.com/celo-org/compliance/issues/7#issuecomment-1895930323))

<img width="1137" alt="image" src="https://github.com/celo-org/compliance/assets/46296830/a9778cb7-d4c6-4cc4-a18b-9546aaf6d524">

**Comment by arthurgousset** [comment]
Unassigning myself because this is something @shazarre has taken on (based on [Slack convo](https://celo-org.slack.com/archives/C0484DDLW5B/p1707133513882109)).

**Comment by aaronmgdr** [comment]
seems like this is still an issue (or a new issue with same symptoms)

**Comment by aaronmgdr** [comment]
@nicolasbrugneaux i think we can close this and just work on #577 or is there other work not related to alerts you want to do?
